class Constants(object):
  GROUP_DATA = "data"
  KEY_TRAINING_FEATURES_FILE = "train_features_file"
  KEY_TRAINING_LABELS_FILE = "train_labels_file"
  KEY_EVALUATION_FEATURES_FILE = "eval_features_file"
  KEY_EVALUATION_LABELS_FILE = "eval_labels_file"
  KEY_FEATURES_VOCAB_FILE = "features_vocab_file"
  KEY_LABELS_VOCAB_FILE = "labels_vocab_file"
  KEY_MAX_FEATURES_LEN = "max_features_len"
  KEY_MAX_LABELS_LEN = "max_labels_len"
  KEY_OUT_DIR = "out_dir"

  GROUP_PARAMS = "params"
  KEY_OPTIMIZER = "optimizer"
  KEY_LEARNING_RATE = "learning_rate"
  KEY_PARAM_INIT = "param_init"
  KEY_CLIP_GRADIENTS = "clip_gradients"
  KEY_REGULARIZATION = "regularization"
  KEY_AVERAGE_LOSS_IN_TIME = "average_loss_in_time"
  KEY_DECAY_TYPE = "decay_type"
  KEY_DECAY_RATE = "decay_rate"
  KEY_DECAY_STEPS = "decay_steps"
  KEY_START_DECAY_STEPS = "start_decay_steps"
  KEY_MIN_LEARNING_RATE = "min_learning_rate"
  KEY_BEAM_WIDTH = "beam_width"
  KEY_REPLACE_UNKNOWN_TARGET = "replace_unknown_target"

  GROUP_TRAIN = "train"
  KEY_TRAINING_BATCH_SIZE = "batch_size"
  KEY_SAVE_CHECKPOINTS_STEPS = "save_checkpoints_steps"
  KEY_KEEP_MAX_CHECKPOINTS = "keep_max_checkpoints"
  KEY_SAVE_SUMMARY_STEPS = "save_summary_steps"
  KEY_TRAINING_STEPS = "training_steps"
  KEY_BUCKET_WIDTH = "bucket_width"
  KEY_SHUFFLE_BUFFER_SIZE = "shuffle_buffer_size"
  KEY_TRAINING_PREFETCH_BUFFER_SIZE = "prefetch_buffer_size"
  KEY_AVERAGE_LAST_CHECKPOINTS = "average_last_checkpoints"

  GROUP_EVAL = "eval"
  KEY_EVAL_BATCH_SIZE = "batch_size"
  KEY_EVAL_PREFETCH_BUFFER_SIZE = "prefetch_buffer_size"
  KEY_EVAL_DELAY = "eval_delay"
  KEY_SAVE_EVAL_PREDICTIONS = "save_predictions"
  KEY_EXTERNAL_EVALUATORS = "external_evaluators"
  KEY_EXPORTERS = "exporters"

  GROUP_INFER = "infer"
  KEY_INFER_BATCH_SIZE = "batch_size"
  KEY_INFER_PREFETCH_BUFFER_SIZE = "prefetch_buffer_size"
  KEY_N_BEST = "n_best"
